project_id = "ktdbpakqyjbdpjzsprse"

[functions.analyze-profile-image]
verify_jwt = true

[functions.detect-clothing]
verify_jwt = false

[functions.suggest-outfit]
verify_jwt = true

[functions.search-products]
verify_jwt = false
